# Generated by Django 4.2.7 on 2025-12-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrada",
            name="url_original",
            field=models.URLField(
                blank=True,
                help_text="URL original de la noticia en el sitio madmusic.iccmu.es",
            ),
        ),
    ]
