# Generated by Django 5.2.9 on 2026-01-12 11:18

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_add_intro_and_migrate_body_to_streamfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="header_subtitle",
            field=models.CharField(
                blank=True,
                default="Espacios, géneros y públicos de la música en Madrid (ss. XVII-XX)",
                help_text="Subtítulo del header (carrusel)",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="header_title",
            field=models.CharField(
                blank=True,
                default="MadMusic-CM H2019/HUM-5731",
                help_text="Título principal del header (carrusel)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("accordion_group", 8),
                    ("image", 12),
                    ("quote", 14),
                    ("raw_html", 15),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "h2",
                                "h3",
                                "h4",
                                "ol",
                                "ul",
                                "blockquote",
                                "hr",
                            ],
                            "icon": "doc-full",
                            "label": "Párrafo",
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Título opcional para el grupo de acordeones",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Título del acordeón (visible cuando está colapsado)",
                            "max_length": 255,
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "h2",
                                "h3",
                                "h4",
                                "ol",
                                "ul",
                                "blockquote",
                                "hr",
                            ],
                            "help_text": "Contenido del acordeón (HTML enriquecido)",
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 2), ("content", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.ListBlock",
                        (4,),
                        {
                            "help_text": "Lista de acordeones en este grupo",
                            "min_num": 1,
                        },
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Permitir que múltiples acordeones estén abiertos al mismo tiempo",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Abrir el primer acordeón por defecto",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 1),
                                ("accordions", 5),
                                ("allow_multiple_open", 6),
                                ("first_accordion_open", 7),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": False},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Texto alternativo para accesibilidad",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 9), ("caption", 10), ("alt_text", 11)]],
                        {},
                    ),
                    13: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 13), ("attribution", 10)]],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {
                            "help_text": "HTML crudo - usar con precaución",
                            "icon": "code",
                        },
                    ),
                },
            ),
        ),
    ]
