# Generated by Django 5.2.9 on 2026-01-12 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_homepage_header_subtitle_homepage_header_title_and_more"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThemeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#d11922",
                        help_text="Color principal del sitio (ejemplo: #d11922 para rojo)",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#c1272d",
                        help_text="Color secundario (ejemplo: #c1272d para rojo oscuro)",
                        max_length=7,
                    ),
                ),
                (
                    "background_gradient_start",
                    models.CharField(
                        default="#34495e",
                        help_text="Color de inicio del gradiente del header",
                        max_length=7,
                    ),
                ),
                (
                    "background_gradient_end",
                    models.CharField(
                        default="#2c3e50",
                        help_text="Color final del gradiente del header",
                        max_length=7,
                    ),
                ),
                (
                    "text_primary",
                    models.CharField(
                        default="#333333",
                        help_text="Color del texto principal",
                        max_length=7,
                    ),
                ),
                (
                    "text_light",
                    models.CharField(
                        default="#ffffff",
                        help_text="Color del texto claro (sobre fondos oscuros)",
                        max_length=7,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Theme Settings",
                "verbose_name_plural": "Theme Settings",
            },
        ),
    ]
