# Generated by Django 5.2.9 on 2026-01-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_themesettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="themesettings",
            name="primary_color",
            field=models.CharField(
                default="#d11922", help_text="Color principal del sitio", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="themesettings",
            name="secondary_color",
            field=models.CharField(
                default="#c1272d", help_text="Color secundario", max_length=7
            ),
        ),
    ]
