# Generated by Django 5.2.9 on 2026-01-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_alter_themesettings_primary_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="background_gradient_end",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Gradiente header - fin (deja vacío para usar #2c3e50)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="background_gradient_start",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Gradiente header - inicio (deja vacío para usar #34495e)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="primary_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Color principal (deja vacío para usar #d11922)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="secondary_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Color secundario (deja vacío para usar #c1272d)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="accent_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Color de acento para títulos/enlaces (deja vacío para heredar de HomePage)",
                max_length=7,
            ),
        ),
    ]
